#!/bin/bash
#
# This bash script uses the git grep command to search for the triggering of events
# and listening to events in a zend framework 2 application and creates a formatted output.
# 
# It works only well, if you ommit multiline calls and do not use variables or constants as
# event name.
#
# @author Alexander During
# @source https://github.com/alexanderduring/notes/blob/master/zendframework2/event-inspector
#

echo -e '\n\E[37;44m Event Inspector (C) 2016 by Alexander During \E[37;40m Lists events in your zend framework 2 application \033[0m\n'

EVENTS=`git grep ">trigger(" | sed -n 's/.*>trigger(\([^,]*\),.*/\1/p' | sort -u`

for event in $EVENTS; do
    printf "\nEvent: $event\n\n"

    TRIGGER_FILES=`git grep --files-with-matches --full-name ">trigger($event"`
    echo -e "  \e[92mTriggered in:\e[39m"
    for file in $TRIGGER_FILES; do
        printf "    < %s\n" $file
    done
    printf "\n"

    LISTENER_FILES=` git grep --files-with-matches --full-name ">attach(.*$event"`
    echo -e "  \e[93mListened in:\e[39m"
    for file in $LISTENER_FILES; do
        printf "    > %s\n" $file
    done
    printf "\n"
done

echo

