#!/bin/bash
#
# This bash script uses the git grep command to search for the triggering of events
# and listening to events in a zend framework 2 application and creates a formatted output.
# 
# It works only well, if you ommit multiline calls and do not use variables or constants as
# event name.
#
# @author Alexander During
#

echo -e '\n\E[37;44m Event Inspector (C) 2016 by Alexander During \E[37;40m List events in your zend framework 2 application \033[0m\n'

EVENTS=`git grep ">trigger(" | sed -n 's/.*>trigger(\([^,]*\),.*/\1/p' | sort`

for event in $EVENTS; do
    printf "\nEvent: $event\n\n"

    TRIGGER_FILES=`git grep --files-with-matches --full-name ">trigger($event"`
    printf "Triggered in:\n"
    for file in $TRIGGER_FILES; do
        printf "< %s\n" $file
    done
    printf "\n"

    LISTENER_FILES=` git grep --files-with-matches --full-name ">attach(.*$event"`
    printf "Listened in:\n"
    for file in $LISTENER_FILES; do
        printf "> %s\n" $file
    done
    printf "\n"
done
